-- FÖRBERED, EJ KÖRD. Kräver Vidars/IT-stöds godkännande och körning i SQL-editorn.
-- Uppdaterad 2026-09-28 efter granskning av Agent - CRM: två kritiska fel rättade
-- (dubbelpostning till fel webhook, och saknat obligatoriskt fält 'slot').
-- OBS 2026-09-29: 20260929140000_attribution_columns_prepared.sql lägger senare till
-- landing_path/referrer_category/utm_* och ersätter notify_booking_webhook() igen med de
-- fälten inkluderade. Ordningen är medveten — den här filens funktion skapas FÖRST utan dem
-- (kolumnerna finns inte än när den här filen körs), sedan bygger nästa migration vidare.
--
-- Bakgrund: bokningsformuläret (BookingWidget.tsx, bakom flaggan BOOKING_ENABLED i
-- src/lib/booking.ts) skriver idag in i quote_requests precis som alla andra formulär.
-- Den här migrationen lägger till en EGEN trigger som postar bokningar till CRM:s
-- dedikerade bokningsendpoint (kontrakt levererat av Agent - CRM, 2026-09-28):
--   POST /api/public/booking-request
--   Header: X-Webhook-Secret: <samma hemlighet som saljtak_secret>
--   Body: { id, name, phone, email, municipality, slot, date, message, utm }
--   slot måste vara exakt "formiddag" | "eftermiddag" | "ring_mig". date krävs om slot
--   inte är ring_mig. Fördelen: CRM sätter booking_slot/callback_requested och räknar ut
--   sla_promised_at server-side i stället för att vi gissar det i frontend.
--
-- VIKTIGT (CRM:s fynd 1): den BEFINTLIGA triggern trg_notify_saljtak_on_new_quote körde
-- tidigare på ALLA rader i quote_requests, inklusive bokningar, och skulle ha postat samma
-- rad till BÅDA webhookarna (två separata leads i CRM, inte en dubblett som upptäcks).
-- Den måste därför uteslutas för bokningsrader (samma villkor som den nya triggern).
--
-- Så aktiveras det (körs manuellt av Vidar/IT-stöd, inte av en agent):
-- 1. Kör hela filen (allt nedan, i ordning) i SQL-editorn för webbsidans projekt.
-- 2. INSERT/UPDATE en rad i webhook_config: key='booking_url',
--    value='https://admin-vt6.tejnevidar.workers.dev/api/public/booking-request'.
--    (Hemligheten är redan satt som saljtak_secret och återanvänds, inget nytt secret.)
-- 3. Uppdatera webbsida/src/components/BookingWidget.tsx så att insert-anropet fyller
--    booking_slot och booking_date (kolumnerna som skapas nedan) och tar med utm-fälten
--    (source/medium/campaign/term/content — content och term saknas i dagens utm.ts och
--    behöver läggas till där också).
-- 4. Live-testa en bokning och bekräfta i CRM att lead_id + sla_promised_at kommer tillbaka,
--    och att INGEN dubblettlead skapas i den vanliga leadlistan.
-- 5. Sätt BOOKING_ENABLED = true i webbsida/src/lib/booking.ts (egen commit, efter att
--    designen visats för och godkänts av Vidar) och slå på länkar till /boka-takkontroll.

-- 1) Strukturerade kolumner för bokningsdata (additiv, påverkar inga befintliga rader).
-- ALTER TABLE public.quote_requests
--   ADD COLUMN IF NOT EXISTS booking_slot TEXT,   -- 'formiddag' | 'eftermiddag' | 'ring_mig'
--   ADD COLUMN IF NOT EXISTS booking_date DATE;   -- null när booking_slot = 'ring_mig'

-- 2) Uteslut bokningar ur den BEFINTLIGA leadwebhooken (CRM:s fynd 1). Samma funktionskropp
--    som idag, bara det nya IF-blocket allra överst är nytt.
-- CREATE OR REPLACE FUNCTION public.notify_saljtak_on_new_quote()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- SET search_path = public, extensions, net
-- AS $$
-- DECLARE
--   v_url TEXT;
--   v_secret TEXT;
-- BEGIN
--   IF NEW.message LIKE 'Bokning kostnadsfri takkontroll%' THEN
--     RETURN NEW; -- bokningar går via trg_notify_booking_webhook i stället, se nedan
--   END IF;
--   SELECT value INTO v_url FROM public.webhook_config WHERE key = 'saljtak_url';
--   SELECT value INTO v_secret FROM public.webhook_config WHERE key = 'saljtak_secret';
--   IF v_url IS NULL OR v_secret IS NULL THEN
--     RAISE WARNING 'Sälj tak webhook ej konfigurerad - hoppar över';
--     RETURN NEW;
--   END IF;
--   PERFORM net.http_post(
--     url := v_url,
--     headers := jsonb_build_object('Content-Type', 'application/json', 'X-Webhook-Secret', v_secret),
--     body := jsonb_build_object(
--       'id', NEW.id::text, 'mode', NEW.mode::text, 'name', NEW.name, 'phone', NEW.phone,
--       'email', NEW.email, 'address', NEW.address, 'current_roof', NEW.current_roof,
--       'new_roof', NEW.new_roof, 'raspont', NEW.raspont, 'gangbrygga', NEW.gangbrygga,
--       'takstege', NEW.takstege, 'avvattning', NEW.avvattning, 'floors', NEW.floors,
--       'message', NEW.message, 'created_at', NEW.created_at::text
--     )
--   );
--   RETURN NEW;
-- END;
-- $$;

-- 3) Ny trigger: bara bokningar, till CRM:s dedikerade endpoint, med 'slot'/'date'/'utm'
--    (CRM:s fynd 2 — slot är obligatoriskt i deras zod-validering, saknas gav 400 på varje
--    bokning). utm läses ur message-raden "Kampanj: source=..., medium=..." (se
--    src/lib/utm.ts) tills BookingWidget.tsx skickar in strukturerade utm-fält direkt.
-- CREATE OR REPLACE FUNCTION public.notify_booking_webhook()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- SET search_path = public, extensions, net
-- AS $$
-- DECLARE
--   v_url TEXT;
--   v_secret TEXT;
-- BEGIN
--   IF NEW.message NOT LIKE 'Bokning kostnadsfri takkontroll%' THEN
--     RETURN NEW; -- bara riktiga bokningar
--   END IF;
--   IF NEW.booking_slot IS NULL THEN
--     RAISE WARNING 'Bokning utan booking_slot - hoppar över webhook (uppdatera BookingWidget.tsx enligt steg 3 ovan)';
--     RETURN NEW;
--   END IF;
--   SELECT value INTO v_url FROM public.webhook_config WHERE key = 'booking_url';
--   SELECT value INTO v_secret FROM public.webhook_config WHERE key = 'saljtak_secret';
--   IF v_url IS NULL OR v_secret IS NULL THEN
--     RAISE WARNING 'Bokningswebhook ej konfigurerad - hoppar över';
--     RETURN NEW;
--   END IF;
--   PERFORM net.http_post(
--     url := v_url,
--     headers := jsonb_build_object('Content-Type', 'application/json', 'X-Webhook-Secret', v_secret),
--     body := jsonb_build_object(
--       'id', NEW.id::text, 'name', NEW.name, 'phone', NEW.phone,
--       'email', NULLIF(NEW.email, ''), 'municipality', NEW.address,
--       'slot', NEW.booking_slot, 'date', NEW.booking_date::text,
--       'message', NEW.message, 'created_at', NEW.created_at::text
--       -- 'utm', jsonb_build_object(...) -- läggs till när BookingWidget.tsx skickar strukturerad utm
--     )
--   );
--   RETURN NEW;
-- END;
-- $$;
--
-- DROP TRIGGER IF EXISTS trg_notify_booking_webhook ON public.quote_requests;
-- CREATE TRIGGER trg_notify_booking_webhook
--   AFTER INSERT ON public.quote_requests
--   FOR EACH ROW
--   EXECUTE FUNCTION public.notify_booking_webhook();
